#!/usr/bin/env bash
frontend http_front
        bind *:80
        bind *:443 ssl crt /etc/haproxy/certs/www.laamyry.tech.pem
        redirect scheme https code 301 if !{ ssl_fc }
        default_backend my_backend

backend my_backend
        balance roundrobin
        server 390145-web-01 100.26.132.85:80 check
        server 390145-web-02 100.26.167.53:80 check
