#!/usr/bin/bash
# transfers a file from our client to a server
if [ "$#" -lt 3 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
	exit 1
fi

if [ "$#" -eq 4 ]; then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi