#!/usr/bin/env bash

# Install nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Create HTML.
echo "Hello World!" > /var/www/html/index.html

# run nginx service
service nginx start
