#!/usr/bin/env bash
# Install nginx web server

# update sys and install nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# lestening on port 80
sudo ufw 'Nginx HTTP'

# Create index HTML.
echo "Hello World!" | sudo tee /var/www/html/index.html

# test if works
sudo nginx -t

# reload nginx service
sudo service nginx reload
