#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

# update sys and install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx

# Create index HTML.
echo "Hello World!" | sudo tee /var/www/html/index.html

# edit default file
replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/laamyry permanent ; "
sudo sed -i "s/server_name _;/$replace/g" /etc/nginx/sites-available/default

# create 404.html
echo "Ceci n'est pas une page." | sudo tee /usr/share/nginx/html/404.html

# edit default file
replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replace/" /etc/nginx/sites-available/default

# restart nginx service
sudo service nginx restart

# reload nginx service
sudo service nginx reload
