#!/usr/bin/bash
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu machine to the requirements asked in this task.

# update sys and install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx

# edit default file
header="\\\tadd_header X-Served-By $HOSTNAME;\n"
sudo sed -i "38i $header" /etc/nginx/sites-available/default

# test nginx config
sudo nginx -t

# restart nginx service
sudo service nginx restart

# restart nginx reload
sudo service nginx reload
