#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Install HAProxy
sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
        bind *:80
        bind *:443 ssl crt /etc/haproxy/certs/www.laamyry.tech.pem
        redirect scheme https code 301 if !{ ssl_fc }
        default_backend my_backend

backend my_backend
        balance roundrobin
        server 390145-web-01 100.26.132.85:80 check
        server 390145-web-02 100.26.167.53:80 check
EOL

# Enable and start HAProxy service
sudo systemctl enable haproxy
sudo systemctl start haproxy

# Verify HAProxy status
sudo systemctl status haproxy
