#!/usr/bin/env bash

# Install HAProxy
sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOL

# Replace [STUDENT_ID] with your actual student ID
sed -i 's/\[STUDENT_ID\]/your_student_id/g' /etc/haproxy/haproxy.cfg

# Enable and start HAProxy service
sudo systemctl enable haproxy
sudo systemctl start haproxy

# Verify HAProxy status
sudo systemctl status haproxy
