#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.

IP="${1}"

png=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${png} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
