#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
sudo sed -i 's/8080 default/80 default/' /etc/nginx/sites-enabled/default
service nginx restart
sudo pkill -1 nginx
