#!/usr/bin/env bash
# kill apache2
pkill apache2
# Run Nginx as Nginx
chown nginx:nginx /etc/nginx/nginx.conf
# getting chmod permission
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
# start nginx
sudo -u nginx service nginx start
